spring.application.name=finCoreBankApplication
server.port=9797
# MySQL local connection (uncomment if localsetup)
#spring.datasource.url=jdbc:mysql://localhost:3306/fincordb
#spring.datasource.username=root
#spring.datasource.password=

#ONLINE CONFIG FOR MYSQL (comment below 3 line if local setup)
spring.datasource.url=${DB_URL}14370/fincoredb?ssl-mode=REQUIRED # modify url as site provide
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#debugging
logging.level.org.springframework.web=DEBUG
server.error.include-stacktrace=always